name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: golangci-lint
      uses: docker://reviewdog/action-golangci-lint:v1 # pre-build docker image
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        golangci_lint_flags: "--enable-all --exclude-use-default=false -D gochecknoglobals"
    - name: unit tests
      uses: cedrickring/golang-action@1.3.0
